import { app, BrowserWindow, ipcMain, clipboard } from "electron";
import * as fs from "fs/promises";
import * as fsSync from "fs";
import * as path from "path";
import * as pty from "node-pty";
import * as os from "os";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
}

let ptyProcess: any = null;
let mainWindow: BrowserWindow | null = null;
let currentTerminalCwd: string = "";
let terminalSilenceUntilNewline = false;
let commandBuffer: string = "";
let currentUserId: string | null = null;
let currentClassName: string | null = null;

// The IDE root is scoped to the specific class:
// ScholarIDE-Workspace/{userId}/{ClassName}/
const getWorkspacePath = (): string => {
  const base = path.join(app.getPath("userData"), "ScholarIDE-Workspace");
  if (!currentUserId) return base;

  const userBase = path.join(base, currentUserId);
  if (currentClassName) {
    const safeClassName = currentClassName.replace(/[^a-z0-9]/gi, "_");
    return path.join(userBase, safeClassName);
  }
  return userBase;
};

// Security: Validate that a path is within the workspace
const validatePath = (targetPath: string): string => {
  const base = path.join(app.getPath("userData"), "ScholarIDE-Workspace");
  const validationRoot = currentUserId ? path.join(base, currentUserId) : base;

  const resolvedPath = path.resolve(targetPath);

  if (!resolvedPath.startsWith(validationRoot)) {
    throw new Error("Access denied: Path is outside workspace");
  }

  return resolvedPath;
};

// Initialize workspace directory
const initializeWorkspace = async (): Promise<void> => {
  const workspacePath = getWorkspacePath();

  try {
    await fs.access(workspacePath);
  } catch {
    // Workspace doesn't exist, create it
    await fs.mkdir(workspacePath, { recursive: true });
    
    // Seed directory integrity
    const rootIntegrity = path.join(workspacePath, '.scholaride.dir');
    await fs.writeFile(rootIntegrity, 'authorized', 'utf-8');
  }
};

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    titleBarStyle: process.platform === "darwin" ? "hiddenInset" : "default",
    titleBarOverlay:
      process.platform !== "darwin"
        ? {
            color: "#252526",
            symbolColor: "#cccccc",
          }
        : false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
      webSecurity: process.env.NODE_ENV === "production" ? true : false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  mainWindow.on("closed", () => {
    mainWindow = null;
  });

  // Native Menu Setup for Mac
  const { Menu } = require("electron");
  const template: any[] = [
    ...(process.platform === "darwin"
      ? [
          {
            label: app.name,
            submenu: [
              { role: "about" },
              { type: "separator" },
              { role: "services" },
              { type: "separator" },
              { role: "hide" },
              { role: "hideOthers" },
              { role: "unhide" },
              { type: "separator" },
              { role: "quit" },
            ],
          },
        ]
      : []),
    {
      label: "File",
      submenu: [
        {
          label: "Open Folder...",
          accelerator: "CmdOrCtrl+O",
          click: () => {
            if (
              mainWindow &&
              !mainWindow.isDestroyed() &&
              mainWindow.webContents &&
              !mainWindow.webContents.isDestroyed()
            ) {
              try {
                mainWindow.webContents.send("menu-open-folder");
              } catch (e) {}
            }
          },
        },
        { type: "separator" },
        { role: "quit" },
      ],
    },
    {
      label: "Edit",
      submenu: [
        { role: "undo" },
        { role: "redo" },
        { type: "separator" },
        { role: "cut" },
        { role: "copy" },
        { role: "paste" },
      ],
    },
    {
      label: "View",
      submenu: [
        { role: "reload" },
        { role: "forceReload" },
        { role: "toggleDevTools" },
        { type: "separator" },
        { role: "resetZoom" },
        { role: "zoomIn" },
        { role: "zoomOut" },
        { type: "separator" },
        { role: "togglefullscreen" },
      ],
    },
  ];

  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);
};

// --- Terminal & PTY Setup ---
const createPty = (cwd: string) => {
  if (ptyProcess) {
    try {
      ptyProcess.kill();
    } catch (e) {}
  }

  // Ensure we start in the workspace
  const workspacePath = getWorkspacePath();
  const safeCwd = cwd.startsWith(workspacePath) ? cwd : workspacePath;
  currentTerminalCwd = safeCwd;

  const shell = process.platform === "win32" ? "powershell.exe" : "zsh";
  // Use -f on Mac to skip startup files and prevent 'compdef' errors from system scripts
  const args: string[] = process.platform === "darwin" ? ["-f"] : [];

  const env: Record<string, string | undefined> = {
    ...process.env,
    TERM: "xterm-256color",
    HOME: workspacePath,
    USERPROFILE: workspacePath,
  };

  // Aggressively clean up environment variables to prevent leaks and Zsh errors
  delete env.npm_config_prefix;
  delete env.ZSH; // Oh-My-Zsh
  delete env.FPATH; // Zsh completion path
  delete env.ZSH_COMPDUMP; // Zsh completion dump
  delete env.ZDOTDIR; // Zsh config dir

  // Set a minimal safe PATH if on Unix
  if (process.platform !== "win32") {
    env.PATH = "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";
  }

  ptyProcess = pty.spawn(shell, args, {
    name: "xterm-color",
    cols: 80,
    rows: 24,
    cwd: safeCwd,
    env: env as any,
  });

  ptyProcess.onData((data: string) => {
    if (terminalSilenceUntilNewline) {
      const nlIndex = data.indexOf("\n");
      if (nlIndex !== -1) {
        terminalSilenceUntilNewline = false;
        const remaining = data.substring(nlIndex + 1);
        if (
          remaining &&
          mainWindow &&
          !mainWindow.isDestroyed() &&
          mainWindow.webContents
        ) {
          mainWindow.webContents.send("terminal-data", remaining);
        }
      }
      return;
    }
    if (
      mainWindow &&
      !mainWindow.isDestroyed() &&
      mainWindow.webContents &&
      !mainWindow.webContents.isDestroyed()
    ) {
      try {
        mainWindow.webContents.send("terminal-data", data);
      } catch (e) {
        console.warn("Failed to send terminal data:", e);
      }
    }
  });
};

const validateCommand = (
  cmdLine: string,
): { allowed: boolean; reason?: string } => {
  const workspacePath = getWorkspacePath();
  const commands = cmdLine.split(/[;&|]/);

  for (let cmd of commands) {
    const trimmedCmd = cmd.trim();
    if (!trimmedCmd) continue;

    const cdMatch = trimmedCmd.match(/^cd(?:\s+(.*))?$/);
    if (cdMatch) {
      const targetPath = (cdMatch[1] || "").trim().replace(/['"]/g, "");

      let resolvedPath;
      if (!targetPath || targetPath === "~") {
        resolvedPath = workspacePath;
      } else if (targetPath.startsWith("~")) {
        resolvedPath = path.resolve(
          workspacePath,
          targetPath.substring(1).replace(/^[\\/]+/, ""),
        );
      } else {
        resolvedPath = path.resolve(currentTerminalCwd, targetPath);
      }

      if (!resolvedPath.startsWith(workspacePath)) {
        return {
          allowed: false,
          reason: `Access denied: Cannot navigate outside workspace (${path.basename(workspacePath)})\r\n`,
        };
      }

      if (
        fsSync.existsSync(resolvedPath) &&
        fsSync.statSync(resolvedPath).isDirectory()
      ) {
        currentTerminalCwd = resolvedPath;
      }
    }

    const pathRegex = /(?:^|\s)((?:\/|~|\.\.\/)[^\s;&|]*)/g;
    let match;
    while ((match = pathRegex.exec(trimmedCmd)) !== null) {
      const p = match[1];
      if (!p) continue;

      let resolved;
      if (p.startsWith("~")) {
        resolved = path.resolve(
          workspacePath,
          p.substring(1).replace(/^[\\/]+/, ""),
        );
      } else if (path.isAbsolute(p) || p.includes("..")) {
        resolved = path.resolve(currentTerminalCwd, p);
      }
    }

    const cmdParts = trimmedCmd.split(/\s+/);
    const cmdName = cmdParts[0]?.toLowerCase();
    const blocked = [
      "mkdir", "rmdir", "rm", "cp", "mv", "scp", "rsync", 
      "touch", "tee", "ln", "link", "mkfile", "mktemp",
      "curl", "wget"
    ];
    
    if (blocked.includes(cmdName)) {
      return {
        allowed: false,
        reason: `Access denied: '${cmdName}' is restricted. Use the Assignments panel or IDE controls.\r\n`,
      };
    }

    // Block redirection which can create/overwrite files
    if (trimmedCmd.includes(">") || trimmedCmd.includes(">>")) {
      return {
        allowed: false,
        reason: "Access denied: Redirection ('>') is restricted to prevent unauthorized file creation.\r\n",
      };
    }
  }

  return { allowed: true };
};

// Initialize terminal state
currentTerminalCwd = getWorkspacePath();

ipcMain.on("terminal-input", (event, data) => {
  if (!ptyProcess) return;

  for (let i = 0; i < data.length; i++) {
    const char = data[i];
    if (char === "\r") {
      const validation = validateCommand(commandBuffer);
      if (!validation.allowed) {
        if (
          mainWindow &&
          !mainWindow.isDestroyed() &&
          mainWindow.webContents &&
          !mainWindow.webContents.isDestroyed()
        ) {
          try {
            mainWindow.webContents.send(
              "terminal-data",
              `\r\n${validation.reason}`,
            );
          } catch (e) {}
        }
        commandBuffer = "";
        ptyProcess.write("\x03");
        return;
      }
      commandBuffer = "";
    } else if (char === "\x7f" || char === "\b") {
      if (commandBuffer.length > 0) {
        commandBuffer = commandBuffer.slice(0, -1);
      }
    } else if (char.charCodeAt(0) >= 32) {
      commandBuffer += char;
    }
  }

  ptyProcess.write(data);
});

ipcMain.on("terminal-resize", (event, { cols, rows }) => {
  if (ptyProcess) ptyProcess.resize(cols, rows);
});

ipcMain.on("terminal-set-cwd", (event, cwd) => {
  const workspacePath = getWorkspacePath();
  const safeCwd = cwd.startsWith(workspacePath) ? cwd : workspacePath;
  createPty(safeCwd);
});

ipcMain.on("terminal-run-file", (event, relPath) => {
  if (!ptyProcess) return;

  const workspacePath = getWorkspacePath();
  
  // Use a smart silence: we silence the PTY data being sent to the renderer 
  // until we see the newline that terminates the command we just sent.
  // This cleanly hides the 'cd' and the 'python3' echo entirely.
  const command = ` cd "${workspacePath}" && python3 "${relPath}"\n`;

  // Validation
  const validation = validateCommand(`cd "${workspacePath}" && python3 "${relPath}"`);
  if (!validation.allowed) {
    if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send("terminal-data", `\r\n${validation.reason}`);
    }
    return;
  }

  terminalSilenceUntilNewline = true;
  ptyProcess.write(command);
  
  // Safety timeout in case the newline isn't detected (e.g. shell error)
  setTimeout(() => {
    terminalSilenceUntilNewline = false;
  }, 1000);
});

// IPC Handlers
ipcMain.handle("ai-chat", async (event, payload) => {
  const { messages } = payload || {};

  console.log("[AI Tutor] Sending request to backend:", {
    url: "http://localhost:1234/api/ai/chat",
    messageCount: messages?.length,
  });

  try {
    if (!messages) {
      throw new Error("No messages provided in request payload");
    }

    const response = await fetch("http://localhost:1234/api/ai/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({ messages }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Server responded with ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    return data;
  } catch (error: any) {
    console.error("[AI Tutor] IPC Chat Handler Error:", error);
    throw error;
  }
});

ipcMain.handle("get-workspace-path", () => {
  return getWorkspacePath();
});

ipcMain.handle("list-directory", async (event, dirPath) => {
  try {
    const absolutePath = path.isAbsolute(dirPath)
      ? dirPath
      : path.join(getWorkspacePath(), dirPath);
    const validatedPath = validatePath(absolutePath);
    const entries = await fs.readdir(validatedPath, { withFileTypes: true });
    return entries
      .filter(
        (entry) =>
          !entry.name.startsWith(".") &&
          !entry.name.endsWith(".scholaride.hash") &&
          entry.name !== "__pycache__" &&
          !entry.name.endsWith(".pyc") &&
          !entry.name.endsWith(".pyo"),
      )
      .map((entry) => ({
        name: entry.name,
        isDirectory: entry.isDirectory(),
        path: path.resolve(validatedPath, entry.name),
      }));
  } catch (error: any) {
    if (error.code !== "ENOENT") {
      console.error("Error listing directory:", error);
    }
    return [];
  }
});

ipcMain.handle("read-file", async (event, filePath) => {
  try {
    const validatedPath = validatePath(filePath);
    return await fs.readFile(validatedPath, "utf-8");
  } catch (error: any) {
    if (error.code === 'ENOENT') return null;
    console.error("Error reading file:", error);
    throw error;
  }
});

ipcMain.handle("write-file", async (event, filePath, content) => {
  let validatedPath: string;
  try {
    validatedPath = validatePath(filePath);

    // Mark this path as being written internally
    internalWritePaths.add(validatedPath);

    // Update the snapshot BEFORE writing to prevent race condition
    fileSnapshots.set(validatedPath, {
      content,
      mtime: Date.now(),
      hash: hashContent(content),
    });

    const hash = hashContent(content);
    const parentDir = path.dirname(validatedPath);
    await fs.mkdir(parentDir, { recursive: true });
    
    await fs.writeFile(validatedPath, content, "utf-8");
    await saveIntegrityHash(validatedPath, content);

    // Update the snapshot with actual mtime after write
    const stats = await fs.stat(validatedPath);
    fileSnapshots.set(validatedPath, {
      content,
      mtime: stats.mtimeMs,
      hash,
    });

    // Remove from internal write set after a brief delay
    setTimeout(() => internalWritePaths.delete(validatedPath), 100);
    return true;
  } catch (error) {
    if (validatedPath) internalWritePaths.delete(validatedPath);
    console.error("Error writing file:", error);
    throw error;
  }
});

ipcMain.handle("create-file", async (event, filePath) => {
  let validatedPath: string;
  try {
    validatedPath = validatePath(filePath);

    // Mark this path as being written internally
    internalWritePaths.add(validatedPath);

    // Update the snapshot BEFORE writing
    fileSnapshots.set(validatedPath, {
      content: "",
      mtime: Date.now(),
      hash: hashContent(""),
    });

    const parentDir = path.dirname(validatedPath);
    await fs.mkdir(parentDir, { recursive: true });

    await fs.writeFile(validatedPath, "", "utf-8");
    await saveIntegrityHash(validatedPath, "");

    // Update the snapshot with actual mtime
    const stats = await fs.stat(validatedPath);
    const hash = hashContent("");
    fileSnapshots.set(validatedPath, {
      content: "",
      mtime: stats.mtimeMs,
      hash,
    });

    // Remove from internal write set after a brief delay
    setTimeout(() => internalWritePaths.delete(validatedPath), 100);
    return true;
  } catch (error) {
    if (validatedPath) internalWritePaths.delete(validatedPath);
    console.error("Error creating file:", error);
    throw error;
  }
});

ipcMain.handle("list-all-files", async (event, dirPath) => {
  const files: Array<{ path: string; content: string }> = [];
  try {
    const absolutePath = path.isAbsolute(dirPath)
      ? dirPath
      : path.join(getWorkspacePath(), dirPath);
    const validatedPath = validatePath(absolutePath);

    const scan = async (currentPath: string) => {
      const entries = await fs.readdir(currentPath, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = path.join(currentPath, entry.name);
        
        // Skip hidden files, integrity files, and python cache
        if (
            entry.name.startsWith('.') || 
            entry.name.endsWith('.scholaride.hash') ||
            entry.name === "__pycache__" ||
            entry.name.endsWith(".pyc") ||
            entry.name.endsWith(".pyo")
        ) continue;
        
        const ignored = ["node_modules", ".git", ".DS_Store", "dist", "out", "build", "__pycache__"];
        if (ignored.includes(entry.name)) continue;

        if (entry.isDirectory()) {
          await scan(fullPath);
        } else if (entry.isFile()) {
          const content = await fs.readFile(fullPath, "utf-8");
          const relativePath = path.relative(validatedPath, fullPath);
          files.push({ path: relativePath, content });
        }
      }
    };

    await scan(validatedPath);
    return files;
  } catch (error) {
    console.error("Error listing all files:", error);
    return [];
  }
});

ipcMain.handle("create-directory", async (event, dirPath) => {
  let validatedPath: string;
  try {
    validatedPath = validatePath(dirPath);
    
    // Mark as internal
    internalWritePaths.add(validatedPath);
    
    await fs.mkdir(validatedPath, { recursive: true });
    
    // Create an integrity sidecar for the directory itself
    const integrityPath = path.join(validatedPath, '.scholaride.dir');
    await fs.writeFile(integrityPath, 'authorized', 'utf-8');
    if (process.platform === 'darwin') {
        const { exec } = require('child_process');
        try { exec(`chflags hidden "${integrityPath}"`); } catch(e) {}
    }

    directorySnapshots.add(validatedPath);
    setTimeout(() => internalWritePaths.delete(validatedPath), 1000);
    return true;
  } catch (error) {
    if (validatedPath) internalWritePaths.delete(validatedPath);
    console.error("Error creating directory:", error);
    throw error;
  }
});

ipcMain.handle("delete-path", async (event, targetPath) => {
  const { shell } = require("electron");
  let validatedPath: string;
  try {
    validatedPath = validatePath(targetPath);

    // Mark this path as being deleted internally
    internalWritePaths.add(validatedPath);
    // 1. Also try to delete the integrity sidecar if it exists
    try {
      const dirname = path.dirname(validatedPath);
      const basename = path.basename(validatedPath);
      const sidecarPath = path.join(dirname, `.${basename}.scholaride.hash`);
      if (fsSync.existsSync(sidecarPath)) {
        await fs.unlink(sidecarPath);
      }
    } catch (e) {
      // Safe to ignore
    }
    
    await shell.trashItem(validatedPath);

    // Remove from tracking
    fileSnapshots.delete(validatedPath);
    directorySnapshots.delete(validatedPath);

    // Remove from internal write set after 1 second to give Chokidar time to settle
    setTimeout(() => internalWritePaths.delete(validatedPath), 1000);
    return true;
  } catch (error) {
    if (validatedPath) internalWritePaths.delete(validatedPath);
    console.error("Error deleting path:", error);
    throw error;
  }
});

ipcMain.handle("get-app-path", () => {
  return app.getAppPath();
});

// File tracking system to block external edits
// Now includes offline integrity via hidden sidecar files
interface FileSnapshot {
  content: string;
  mtime: number;
  hash: string;
}

const getIntegrityPath = (filePath: string) => {
  const dir = path.dirname(filePath);
  const name = path.basename(filePath);
  return path.join(dir, `.${name}.scholaride.hash`);
};

const saveIntegrityHash = async (filePath: string, content: string) => {
  try {
    const integrityPath = getIntegrityPath(filePath);
    const hash = hashContent(content);
    await fs.writeFile(integrityPath, hash, "utf-8");
    // On Mac, make it hidden if it's not already starting with '.' (redundant but safe)
    if (process.platform === "darwin") {
      try {
        const { exec } = require("child_process");
        exec(`chflags hidden "${integrityPath}"`);
      } catch (e) {}
    }
  } catch (e) {
    console.error("Failed to save integrity hash:", e);
  }
};

const getStoredIntegrityHash = async (
  filePath: string,
): Promise<string | null> => {
  try {
    const integrityPath = getIntegrityPath(filePath);
    return await fs.readFile(integrityPath, "utf-8");
  } catch {
    return null;
  }
};

const fileSnapshots = new Map<string, FileSnapshot>();
const directorySnapshots = new Set<string>();
const internalWritePaths = new Set<string>();
const openFiles = new Set<string>(); // Track files currently open in editor
let currentWatcher: fsSync.FSWatcher | null = null;

// IPC handler to track which files are open
ipcMain.on("file-opened", (event, filePath) => {
  openFiles.add(filePath);
  console.log(`[FileTracker] File opened: ${filePath}`);
});

ipcMain.on("file-closed", (event, filePath) => {
  openFiles.delete(filePath);
  console.log(`[FileTracker] File closed: ${filePath}`);
});

// Generate a SHA-256 hash for file content (matches Supabase server-side hash)
const hashContent = (content: string): string => {
  const crypto = require("crypto");
  return crypto.createHash("sha256").update(content).digest("hex");
};

// Scan and track all files in the workspace
const scanAndTrackFiles = async (dirPath: string): Promise<void> => {
  try {
    const entries = await fs.readdir(dirPath, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dirPath, entry.name);

      // Skip ignored directories and files
      const ignored = [
        "node_modules",
        ".git",
        ".DS_Store",
        ".webpack",
        ".cache",
        "dist",
        "out",
        "build",
        "coverage",
        "__pycache__",
      ];

      if (
        ignored.some((ignore) => entry.name.includes(ignore)) ||
        entry.name.endsWith(".pyc") ||
        entry.name.endsWith(".pyo")
      ) {
        continue;
      }

      if (entry.isDirectory()) {
        directorySnapshots.add(fullPath);
        await scanAndTrackFiles(fullPath);
      } else if (entry.isFile() && !entry.name.endsWith(".scholaride.hash") && !entry.name.endsWith(".scholaride.dir")) {
        try {
          const content = await fs.readFile(fullPath, "utf-8");
          const stats = await fs.stat(fullPath);
          const currentHash = hashContent(content);
          const storedHash = await getStoredIntegrityHash(fullPath);

          if (storedHash && currentHash !== storedHash) {
            console.warn(
              `[Integrity] OFFLINE TAMPERING detected for: ${fullPath}`,
            );

            // Notify the UI immediately, including the expected hash for precise restoration
            if (
              mainWindow &&
              !mainWindow.isDestroyed() &&
              mainWindow.webContents
            ) {
              mainWindow.webContents.send("file-externally-modified", {
                filePath: fullPath,
                action: "offline-tampering",
                expectedHash: storedHash,
              });
            }
          } else if (!storedHash) {
             // NO INTEGRITY RECORD: This file was likely added while the IDE was closed.
             console.warn(`[Integrity] UNKNOWN FILE detected on startup: ${fullPath}`);
             if (
              mainWindow &&
              !mainWindow.isDestroyed() &&
              mainWindow.webContents
            ) {
              mainWindow.webContents.send("file-externally-modified", {
                filePath: fullPath,
                action: "unknown-file-detected",
              });
            }
          }

          fileSnapshots.set(fullPath, {
            content,
            mtime: stats.mtimeMs,
            hash: currentHash,
          });
        } catch (error) {
          // Skip files that can't be read (binary, etc.)
        }
      }
    }
  } catch (error) {
    console.error("Error scanning directory:", error);
  }
};

// Helper to check if a path (or its parent) is currently being modified internally
const isPathWhitelisted = (fullPath: string): boolean => {
  for (const internalPath of internalWritePaths) {
    if (
      fullPath === internalPath ||
      fullPath.startsWith(internalPath + path.sep)
    ) {
      return true;
    }
  }
  return false;
};

// Check if a file change was external and revert if needed
const handleFileChange = async (
  fullPath: string,
  eventType: string,
): Promise<void> => {
  // Ignore if this path or its parent is being written internally
  if (isPathWhitelisted(fullPath)) {
    return;
  }

  try {
    const exists = fsSync.existsSync(fullPath);

    if (!exists) {
      // File was deleted externally
      const snapshot = fileSnapshots.get(fullPath);
      if (snapshot) {
        console.warn(
          `\n⚠️  [FileTracker] EXTERNAL DELETION DETECTED AND BLOCKED\n` +
            `File: ${fullPath}\n` +
            `This file was deleted by an external program or command.\n` +
            `The file has been automatically restored to protect the workspace.\n` +
            `Files in this workspace can ONLY be deleted within ScholarIDE.\n`,
        );

        // Restore the file
        internalWritePaths.add(fullPath);
        await fs.writeFile(fullPath, snapshot.content, "utf-8");
        setTimeout(() => internalWritePaths.delete(fullPath), 100);

        // Notify user
        if (
          mainWindow &&
          !mainWindow.isDestroyed() &&
          mainWindow.webContents &&
          !mainWindow.webContents.isDestroyed()
        ) {
          try {
            mainWindow.webContents.send("file-externally-modified", {
              filePath: fullPath,
              action: "restored-deleted",
            });
          } catch (e) {}
        }
      }
      return;
    }

    const stats = await fs.stat(fullPath);
    const isDirectory = stats.isDirectory();
 
    // Skip hidden integrity files and temporary runtime artifacts
    if (
        fullPath.endsWith(".scholaride.hash") || 
        fullPath.endsWith(".scholaride.dir") ||
        fullPath.includes("__pycache__") ||
        fullPath.endsWith(".pyc") ||
        fullPath.endsWith(".pyo")
    ) {
      return;
    }
 
    if (isDirectory) {
        // Wait a small moment to see if it was an internal creation that hasn't finished yet
        await new Promise(resolve => setTimeout(resolve, 300));
        
        // Re-check whitelist and memory tracking after delay
        if (isPathWhitelisted(fullPath) || directorySnapshots.has(fullPath)) return;
 
        // Check for integrity file on disk as final verification
        const integrityPath = path.join(fullPath, '.scholaride.dir');
        if (!fsSync.existsSync(integrityPath)) {
            console.warn(`\n⚠️  [FileTracker] UNAUTHORIZED DIRECTORY DETECTED\n` +
              `Directory: ${fullPath}\n` +
              `Removing unauthorized folder created externally.\n`);
            
            const { shell } = require('electron');
            internalWritePaths.add(fullPath);
            await shell.trashItem(fullPath);
            setTimeout(() => internalWritePaths.delete(fullPath), 1000);
            return;
        } else {
            // Authorized but missed in memory? Add it now.
            directorySnapshots.add(fullPath);
        }
        return; 
    }

    const snapshot = fileSnapshots.get(fullPath);

    if (snapshot) {
      // File exists in our tracking - check if it was modified externally
      if (stats.mtimeMs > snapshot.mtime + 100) {
        // 100ms tolerance
        const currentContent = await fs.readFile(fullPath, "utf-8");
        const currentHash = hashContent(currentContent);

        if (currentHash !== snapshot.hash) {
          console.warn(
            `\n⚠️  [FileTracker] EXTERNAL EDIT DETECTED AND BLOCKED\n` +
              `File: ${fullPath}\n` +
              `This file was modified by an external program (VS Code, nano, vim, etc.)\n` +
              `The change has been automatically reverted to protect the workspace.\n` +
              `Files in this workspace can ONLY be edited within ScholarIDE.\n`,
          );

          // Revert to our snapshot
          internalWritePaths.add(fullPath);
          await fs.writeFile(fullPath, snapshot.content, "utf-8");
          setTimeout(() => internalWritePaths.delete(fullPath), 100);

          // Notify user
          if (
            mainWindow &&
            !mainWindow.isDestroyed() &&
            mainWindow.webContents &&
            !mainWindow.webContents.isDestroyed()
          ) {
            try {
              mainWindow.webContents.send("file-externally-modified", {
                filePath: fullPath,
                action: "reverted-modification",
              });
            } catch (e) {}
          }
        }
      }
    } else {
      // New file created externally - FLAG FOR VERIFICATION
      console.log(`[FileTracker] Unknown file appearance: ${fullPath}. Requesting cloud verification…`);
      
      if (mainWindow && !mainWindow.isDestroyed() && mainWindow.webContents) {
        mainWindow.webContents.send("file-externally-modified", {
          filePath: fullPath,
          action: "unknown-file-detected",
        });
      }
    }
  } catch (error) {
    console.error(`[FileTracker] Error handling file change:`, error);
  }
};

let auditInterval: NodeJS.Timeout | null = null;

const startWatching = (dirPath: string) => {
  if (currentWatcher) {
    currentWatcher.close();
    currentWatcher = null;
  }
  if (auditInterval) {
    clearInterval(auditInterval);
    auditInterval = null;
  }

  // Initial scan to track all files
  scanAndTrackFiles(dirPath).then(() => {
    console.log(
      `[FileTracker] Tracking ${fileSnapshots.size} files in workspace`,
    );
  });

  // PERIODIC AUDIT: Catch folders missed by flaky fs.watch on macOS
  auditInterval = setInterval(async () => {
    try {
        const entries = await fs.readdir(dirPath, { withFileTypes: true });
        for (const entry of entries) {
            if (entry.isDirectory()) {
                const fullPath = path.join(dirPath, entry.name);
                
                // Skip ignored
                const ignored = ["node_modules", ".git", ".DS_Store", ".vscode", ".idea", ".webpack", ".cache", "dist", "out", "build", "coverage", "__pycache__"];
                if (ignored.includes(entry.name) || entry.name.endsWith(".pyc") || entry.name.endsWith(".pyo")) continue;
                
                // Skip whitelisted or already tracked
                if (isPathWhitelisted(fullPath) || directorySnapshots.has(fullPath)) continue;

                // Check integrity
                const integrityPath = path.join(fullPath, '.scholaride.dir');
                if (!fsSync.existsSync(integrityPath)) {
                    console.warn(`[Integrity Audit] Removing unauthorized directory: ${entry.name}`);
                    const { shell } = require('electron');
                    internalWritePaths.add(fullPath);
                    await shell.trashItem(fullPath);
                    setTimeout(() => internalWritePaths.delete(fullPath), 1000);
                } else {
                    directorySnapshots.add(fullPath);
                }
            }
        }
    } catch (e) {
        console.error('[Integrity Audit] Error:', e);
    }
  }, 5000);

  try {
    // Recursive watching is supported on macOS and Windows (mostly)
    currentWatcher = fsSync.watch(
      dirPath,
      { recursive: true },
      async (eventType, filename) => {
        const ignored = [
          "node_modules",
          ".git",
          ".DS_Store",
          ".vscode",
          ".idea",
          ".webpack",
          ".cache",
          "dist",
          "out",
          "build",
          "coverage",
          "Thumbs.db", // Windows
        ];

        if (filename && ignored.some((ignore) => filename.includes(ignore))) {
          return;
        }

        // Build full path
        const fullPath = path.join(dirPath, filename);

        // Handle the file change (check for external edits)
        await handleFileChange(fullPath, eventType);

        // Still send the event to renderer for UI updates
        if (
          mainWindow &&
          !mainWindow.isDestroyed() &&
          mainWindow.webContents &&
          !mainWindow.webContents.isDestroyed()
        ) {
          try {
            mainWindow.webContents.send("file-system-changed", {
              eventType,
              filename,
            });
          } catch (e) {}
        }
      },
    );
  } catch (error) {
    console.error("Failed to start watcher:", error);
  }
};

// Return the workspace path (no dialog - always use workspace)
ipcMain.handle("open-directory", async () => {
  const workspacePath = getWorkspacePath();
  startWatching(workspacePath);
  return workspacePath;
});

// Called when the user logs in/out. Resets class context on logout.
ipcMain.handle("set-user-id", async (_event, userId: string | null) => {
  currentUserId = userId;
  currentClassName = null; // Reset class name on user change
  const workspacePath = getWorkspacePath();

  if (userId) {
    await fs.mkdir(workspacePath, { recursive: true });
  }

  currentTerminalCwd = workspacePath;
  return workspacePath;
});

// Called once the student has joined a class.
// Switches the IDE root to the specific class sub-folder.
ipcMain.handle(
  "set-class-id",
  async (_event, classId: string | null, className?: string | null) => {
    currentClassName = className || null;
    const workspacePath = getWorkspacePath();

    if (currentUserId && className) {
      await fs.mkdir(workspacePath, { recursive: true });

      // Seed directory integrity
      const classIntegrity = path.join(workspacePath, '.scholaride.dir');
      await fs.writeFile(classIntegrity, 'authorized', 'utf-8');
    }

    currentTerminalCwd = workspacePath;
    
    // CRITICAL: Re-initialize and scan the new class folder for offline changes
    await initializeWorkspace();
    
    return workspacePath;
  },
);

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", async () => {
  // Register deep link protocol for OAuth callbacks (e.g. scholaride://auth/callback)
  if (process.defaultApp) {
    // Development: pass the app path as an argument
    app.setAsDefaultProtocolClient("scholaride", process.execPath, [
      app.getAppPath(),
    ]);
  } else {
    app.setAsDefaultProtocolClient("scholaride");
  }

  // Override the CSP header injected by the webpack dev server so that
  // the renderer is allowed to connect to Supabase.
  const { session } = require("electron");
  session.defaultSession.webRequest.onHeadersReceived(
    (
      details: Electron.OnHeadersReceivedListenerDetails,
      callback: (response: Electron.HeadersReceivedResponse) => void,
    ) => {
      const supabaseUrl =
        process.env.SUPABASE_URL || "https://edepqvyytyygdztctzeq.supabase.co";
      const supabaseWss = supabaseUrl.replace(/^http/, "ws");
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          "Content-Security-Policy": [
            `default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' ${supabaseUrl} ${supabaseWss}; worker-src 'self' blob:; font-src 'self' data:;`,
          ],
        },
      });
    },
  );

  await initializeWorkspace();
  createWindow();
  createPty(getWorkspacePath());
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.removeHandler("move-path");
ipcMain.handle(
  "move-path",
  async (_event, oldPath: string, newPath: string) => {
    try {
      const validatedOld = validatePath(oldPath);
      const validatedNew = validatePath(newPath);

      // 1. Mark both paths as internal to prevent self-healing from thinking it's a delete/create cycle
      internalWritePaths.add(validatedOld);
      internalWritePaths.add(validatedNew);

      // 2. Ensure destination directory exists
      await fs.mkdir(path.dirname(validatedNew), { recursive: true });

      // 3. Rename the actual file/folder
      await fs.rename(validatedOld, validatedNew);

      // 4. Update snapshots
      const oldSnapshot = fileSnapshots.get(validatedOld);
      if (oldSnapshot) {
        fileSnapshots.set(validatedNew, oldSnapshot);
        fileSnapshots.delete(validatedOld);
      }

      // 5. If it's a file, try to rename the integrity sidecar too
      const oldDir = path.dirname(validatedOld);
      const oldBase = path.basename(validatedOld);
      const oldSidecar = path.join(oldDir, `.${oldBase}.scholaride.hash`);

      const newDir = path.dirname(validatedNew);
      const newBase = path.basename(validatedNew);
      const newSidecar = path.join(newDir, `.${newBase}.scholaride.hash`);

      try {
        if (fsSync.existsSync(oldSidecar)) {
          await fs.rename(oldSidecar, newSidecar);
        }
      } catch (e) {
        console.warn("[Integrity] Could not move sidecar:", e);
      }

      // Cleanup whitelisting after events process
      setTimeout(() => {
        internalWritePaths.delete(validatedOld);
        internalWritePaths.delete(validatedNew);
      }, 1000);

      return true;
    } catch (error: any) {
      internalWritePaths.delete(oldPath);
      internalWritePaths.delete(newPath);
      console.error("Error moving path:", error);
      throw error;
    }
  },
);

// Handle macOS deep links (app already running)
app.on("open-url", (event, url) => {
  event.preventDefault();
  if (
    mainWindow &&
    !mainWindow.isDestroyed() &&
    mainWindow.webContents &&
    !mainWindow.webContents.isDestroyed()
  ) {
    try {
      mainWindow.webContents.send("oauth-callback", url);
    } catch (e) {}
  }
});

// Handle Windows/Linux deep links (second instance triggered)
app.on("second-instance", (_event, commandLine) => {
  const url = commandLine.find((arg) => arg.startsWith("scholaride://"));
  if (url && mainWindow && !mainWindow.isDestroyed()) {
    try {
      mainWindow.webContents.send("oauth-callback", url);
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    } catch (e) {}
  }
});
// --- Clipboard Handlers for Workspace-Only Copy/Paste ---
let lastInternalHash = "";

const getHash = (text: string) => {
  return require("crypto").createHash("sha256").update(text).digest("hex");
};

ipcMain.on("clipboard-write-internal", (event, text) => {
  console.log("[Main] Writing internal clipboard (Hash approach).");
  lastInternalHash = getHash(text);
  clipboard.writeText(text);
});

ipcMain.handle("clipboard-read-internal", (event) => {
  const text = clipboard.readText();
  const currentHash = getHash(text);
  const isInternal = currentHash === lastInternalHash && text !== "";
  console.log("[Main] Async read. Internal:", isInternal);
  return {
    text,
    isInternal,
  };
});

ipcMain.on("clipboard-is-internal", (event) => {
  const text = clipboard.readText();
  const currentHash = getHash(text);
  const isInternal = currentHash === lastInternalHash && text !== "";
  console.log("[Main] Sync check. Internal:", isInternal, "Hash matches:", currentHash === lastInternalHash);
  event.returnValue = isInternal;
});
