import { app, BrowserWindow, ipcMain } from "electron";
import * as fs from "fs/promises";
import * as fsSync from "fs";
import * as path from "path";
import * as pty from "node-pty";
import * as os from "os";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
}

let ptyProcess: any = null;
let mainWindow: BrowserWindow | null = null;
let currentTerminalCwd: string = "";
let commandBuffer: string = "";
let currentUserId: string | null = null;

// Workspace directory - sandboxed, scoped per signed-in user
const getWorkspacePath = (): string => {
  const base = path.join(app.getPath("userData"), "ScholarIDE-Workspace");
  return currentUserId ? path.join(base, currentUserId) : base;
};

// Security: Validate that a path is within the workspace
const validatePath = (targetPath: string): string => {
  const workspacePath = getWorkspacePath();
  const resolvedPath = path.resolve(targetPath);

  if (!resolvedPath.startsWith(workspacePath)) {
    throw new Error("Access denied: Path is outside workspace");
  }

  return resolvedPath;
};

// Initialize workspace directory
const initializeWorkspace = async (): Promise<void> => {
  const workspacePath = getWorkspacePath();

  try {
    await fs.access(workspacePath);
  } catch {
    // Workspace doesn't exist, create it
    await fs.mkdir(workspacePath, { recursive: true });

    // Create a welcome file
    const welcomeFile = path.join(workspacePath, "welcome.md");
    await fs.writeFile(
      welcomeFile,
      `# Welcome to ScholarIDE!

This is your workspace directory. All your files will be stored here.

## Getting Started

1. Create new files using the file explorer
2. Edit files in the Monaco editor
3. Run Python files with the Run button

Happy coding!
`,
      "utf-8",
    );
  }
};

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    titleBarStyle: process.platform === "darwin" ? "hiddenInset" : "default",
    titleBarOverlay:
      process.platform !== "darwin"
        ? {
            color: "#252526",
            symbolColor: "#cccccc",
          }
        : false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
      webSecurity: process.env.NODE_ENV === "production" ? true : false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  mainWindow.on("closed", () => {
    mainWindow = null;
  });

  // Native Menu Setup for Mac
  const { Menu } = require("electron");
  const template: any[] = [
    ...(process.platform === "darwin"
      ? [
          {
            label: app.name,
            submenu: [
              { role: "about" },
              { type: "separator" },
              { role: "services" },
              { type: "separator" },
              { role: "hide" },
              { role: "hideOthers" },
              { role: "unhide" },
              { type: "separator" },
              { role: "quit" },
            ],
          },
        ]
      : []),
    {
      label: "File",
      submenu: [
        {
          label: "Open Folder...",
          accelerator: "CmdOrCtrl+O",
          click: () => {
            if (
              mainWindow &&
              !mainWindow.isDestroyed() &&
              mainWindow.webContents &&
              !mainWindow.webContents.isDestroyed()
            ) {
              try {
                mainWindow.webContents.send("menu-open-folder");
              } catch (e) {}
            }
          },
        },
        { type: "separator" },
        { role: "quit" },
      ],
    },
    {
      label: "Edit",
      submenu: [
        { role: "undo" },
        { role: "redo" },
        { type: "separator" },
        { role: "cut" },
        { role: "copy" },
        { role: "paste" },
      ],
    },
    {
      label: "View",
      submenu: [
        { role: "reload" },
        { role: "forceReload" },
        { role: "toggleDevTools" },
        { type: "separator" },
        { role: "resetZoom" },
        { role: "zoomIn" },
        { role: "zoomOut" },
        { type: "separator" },
        { role: "togglefullscreen" },
      ],
    },
  ];

  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);
};

// --- Terminal & PTY Setup ---
const createPty = (cwd: string) => {
  if (ptyProcess) {
    try {
      ptyProcess.kill();
    } catch (e) {}
  }

  // Ensure we start in the workspace
  const workspacePath = getWorkspacePath();
  const safeCwd = cwd.startsWith(workspacePath) ? cwd : workspacePath;
  currentTerminalCwd = safeCwd;

  const shell = process.platform === "win32" ? "powershell.exe" : "zsh";
  // Use -f on Mac to skip startup files and prevent 'compdef' errors from system scripts
  const args: string[] = process.platform === "darwin" ? ["-f"] : [];

  const env: Record<string, string | undefined> = {
    ...process.env,
    TERM: "xterm-256color",
    HOME: workspacePath,
    USERPROFILE: workspacePath,
  };

  // Aggressively clean up environment variables to prevent leaks and Zsh errors
  delete env.npm_config_prefix;
  delete env.ZSH; // Oh-My-Zsh
  delete env.FPATH; // Zsh completion path
  delete env.ZSH_COMPDUMP; // Zsh completion dump
  delete env.ZDOTDIR; // Zsh config dir

  // Set a minimal safe PATH if on Unix
  if (process.platform !== "win32") {
    env.PATH = "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";
  }

  ptyProcess = pty.spawn(shell, args, {
    name: "xterm-color",
    cols: 80,
    rows: 24,
    cwd: safeCwd,
    env: env as any,
  });

  ptyProcess.onData((data: string) => {
    if (
      mainWindow &&
      !mainWindow.isDestroyed() &&
      mainWindow.webContents &&
      !mainWindow.webContents.isDestroyed()
    ) {
      try {
        mainWindow.webContents.send("terminal-data", data);
      } catch (e) {
        console.warn("Failed to send terminal data:", e);
      }
    }
  });
};

const validateCommand = (
  cmdLine: string,
): { allowed: boolean; reason?: string } => {
  const workspacePath = getWorkspacePath();
  const commands = cmdLine.split(/[;&|]/);

  for (let cmd of commands) {
    const trimmedCmd = cmd.trim();
    if (!trimmedCmd) continue;

    const cdMatch = trimmedCmd.match(/^cd(?:\s+(.*))?$/);
    if (cdMatch) {
      const targetPath = (cdMatch[1] || "").trim().replace(/['"]/g, "");

      let resolvedPath;
      if (!targetPath || targetPath === "~") {
        resolvedPath = workspacePath;
      } else if (targetPath.startsWith("~")) {
        resolvedPath = path.resolve(
          workspacePath,
          targetPath.substring(1).replace(/^[\\/]+/, ""),
        );
      } else {
        resolvedPath = path.resolve(currentTerminalCwd, targetPath);
      }

      if (!resolvedPath.startsWith(workspacePath)) {
        return {
          allowed: false,
          reason: `Access denied: Cannot navigate outside workspace (${path.basename(workspacePath)})\r\n`,
        };
      }

      if (
        fsSync.existsSync(resolvedPath) &&
        fsSync.statSync(resolvedPath).isDirectory()
      ) {
        currentTerminalCwd = resolvedPath;
      }
    }

    const pathRegex = /(?:^|\s)((?:\/|~|\.\.\/)[^\s;&|]*)/g;
    let match;
    while ((match = pathRegex.exec(trimmedCmd)) !== null) {
      const p = match[1];
      if (!p) continue;

      let resolved;
      if (p.startsWith("~")) {
        resolved = path.resolve(
          workspacePath,
          p.substring(1).replace(/^[\\/]+/, ""),
        );
      } else if (path.isAbsolute(p) || p.includes("..")) {
        resolved = path.resolve(currentTerminalCwd, p);
      }
    }

    const restrictedCmds = ["cp ", "mv ", "scp ", "rsync "];
    if (restrictedCmds.some((prefix) => trimmedCmd.startsWith(prefix))) {
      const parts = trimmedCmd.split(/\s+/);
      for (const part of parts) {
        if (part.startsWith("-")) continue;
        if (
          part === "cp" ||
          part === "mv" ||
          part === "scp" ||
          part === "rsync"
        )
          continue;

        const cleanPart = part.replace(/['"]/g, "");
        if (cleanPart) {
          const resolved = path.resolve(currentTerminalCwd, cleanPart);
          if (
            !resolved.startsWith(workspacePath) &&
            fsSync.existsSync(resolved)
          ) {
            return {
              allowed: false,
              reason: `Access denied: External file operations are restricted\r\n`,
            };
          }
        }
      }
    }
  }

  return { allowed: true };
};

// Initialize terminal state
currentTerminalCwd = getWorkspacePath();

ipcMain.on("terminal-input", (event, data) => {
  if (!ptyProcess) return;

  for (let i = 0; i < data.length; i++) {
    const char = data[i];
    if (char === "\r") {
      const validation = validateCommand(commandBuffer);
      if (!validation.allowed) {
        if (
          mainWindow &&
          !mainWindow.isDestroyed() &&
          mainWindow.webContents &&
          !mainWindow.webContents.isDestroyed()
        ) {
          try {
            mainWindow.webContents.send(
              "terminal-data",
              `\r\n${validation.reason}`,
            );
          } catch (e) {}
        }
        commandBuffer = "";
        ptyProcess.write("\x03");
        return;
      }
      commandBuffer = "";
    } else if (char === "\x7f" || char === "\b") {
      if (commandBuffer.length > 0) {
        commandBuffer = commandBuffer.slice(0, -1);
      }
    } else if (char.charCodeAt(0) >= 32) {
      commandBuffer += char;
    }
  }

  ptyProcess.write(data);
});

ipcMain.on("terminal-resize", (event, { cols, rows }) => {
  if (ptyProcess) ptyProcess.resize(cols, rows);
});

ipcMain.on("terminal-set-cwd", (event, cwd) => {
  const workspacePath = getWorkspacePath();
  const safeCwd = cwd.startsWith(workspacePath) ? cwd : workspacePath;
  createPty(safeCwd);
});

// IPC Handlers
ipcMain.handle("ai-chat", async (event, payload) => {
  const { messages } = payload || {};

  console.log("[AI Tutor] Sending request to backend:", {
    url: "http://localhost:1234/api/ai/chat",
    messageCount: messages?.length,
  });

  try {
    if (!messages) {
      throw new Error("No messages provided in request payload");
    }

    const response = await fetch("http://localhost:1234/api/ai/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({ messages }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Server responded with ${response.status}: ${errorText}`);
    }

    const data = await response.json();
    return data;
  } catch (error: any) {
    console.error("[AI Tutor] IPC Chat Handler Error:", error);
    throw error;
  }
});

ipcMain.handle("get-workspace-path", () => {
  return getWorkspacePath();
});

ipcMain.handle("list-directory", async (event, dirPath) => {
  try {
    const absolutePath = path.isAbsolute(dirPath)
      ? dirPath
      : path.join(getWorkspacePath(), dirPath);
    const validatedPath = validatePath(absolutePath);
    const entries = await fs.readdir(validatedPath, { withFileTypes: true });
    return entries
      .filter((entry) => !entry.name.startsWith("."))
      .map((entry) => ({
        name: entry.name,
        isDirectory: entry.isDirectory(),
        path: path.resolve(validatedPath, entry.name),
      }));
  } catch (error) {
    console.error("Error listing directory:", error);
    return [];
  }
});

ipcMain.handle("read-file", async (event, filePath) => {
  try {
    const validatedPath = validatePath(filePath);
    return await fs.readFile(validatedPath, "utf-8");
  } catch (error) {
    console.error("Error reading file:", error);
    throw error;
  }
});

ipcMain.handle("write-file", async (event, filePath, content) => {
  let validatedPath: string;
  try {
    validatedPath = validatePath(filePath);

    // Mark this path as being written internally
    internalWritePaths.add(validatedPath);

    // Update the snapshot BEFORE writing to prevent race condition
    fileSnapshots.set(validatedPath, {
      content,
      mtime: Date.now(),
      hash: hashContent(content),
    });

    await fs.writeFile(validatedPath, content, "utf-8");

    // Update the snapshot with actual mtime after write
    const stats = await fs.stat(validatedPath);
    fileSnapshots.set(validatedPath, {
      content,
      mtime: stats.mtimeMs,
      hash: hashContent(content),
    });

    // Remove from internal write set after a brief delay
    setTimeout(() => internalWritePaths.delete(validatedPath), 100);
    return true;
  } catch (error) {
    if (validatedPath) internalWritePaths.delete(validatedPath);
    console.error("Error writing file:", error);
    throw error;
  }
});

ipcMain.handle("create-file", async (event, filePath) => {
  let validatedPath: string;
  try {
    validatedPath = validatePath(filePath);

    // Mark this path as being written internally
    internalWritePaths.add(validatedPath);

    // Update the snapshot BEFORE writing
    fileSnapshots.set(validatedPath, {
      content: "",
      mtime: Date.now(),
      hash: hashContent(""),
    });

    await fs.writeFile(validatedPath, "", "utf-8");

    // Update the snapshot with actual mtime
    const stats = await fs.stat(validatedPath);
    fileSnapshots.set(validatedPath, {
      content: "",
      mtime: stats.mtimeMs,
      hash: hashContent(""),
    });

    // Remove from internal write set after a brief delay
    setTimeout(() => internalWritePaths.delete(validatedPath), 100);
    return true;
  } catch (error) {
    if (validatedPath) internalWritePaths.delete(validatedPath);
    console.error("Error creating file:", error);
    throw error;
  }
});

ipcMain.handle("create-directory", async (event, dirPath) => {
  try {
    const validatedPath = validatePath(dirPath);
    await fs.mkdir(validatedPath, { recursive: true });
    return true;
  } catch (error) {
    console.error("Error creating directory:", error);
    throw error;
  }
});

ipcMain.handle("delete-path", async (event, targetPath) => {
  const { shell } = require("electron");
  let validatedPath: string;
  try {
    validatedPath = validatePath(targetPath);

    // Mark this path as being deleted internally
    internalWritePaths.add(validatedPath);
    await shell.trashItem(validatedPath);

    // Remove from tracking
    fileSnapshots.delete(validatedPath);

    // Remove from internal write set after a brief delay
    setTimeout(() => internalWritePaths.delete(validatedPath), 100);
    return true;
  } catch (error) {
    if (validatedPath) internalWritePaths.delete(validatedPath);
    console.error("Error deleting path:", error);
    throw error;
  }
});

ipcMain.handle("get-app-path", () => {
  return app.getAppPath();
});

// File tracking system to block external edits
interface FileSnapshot {
  content: string;
  mtime: number;
  hash: string;
}

const fileSnapshots = new Map<string, FileSnapshot>();
const internalWritePaths = new Set<string>();
const openFiles = new Set<string>(); // Track files currently open in editor
let currentWatcher: fsSync.FSWatcher | null = null;

// IPC handler to track which files are open
ipcMain.on("file-opened", (event, filePath) => {
  openFiles.add(filePath);
  console.log(`[FileTracker] File opened: ${filePath}`);
});

ipcMain.on("file-closed", (event, filePath) => {
  openFiles.delete(filePath);
  console.log(`[FileTracker] File closed: ${filePath}`);
});

// Generate a simple hash for file content
const hashContent = (content: string): string => {
  const crypto = require("crypto");
  return crypto.createHash("md5").update(content).digest("hex");
};

// Scan and track all files in the workspace
const scanAndTrackFiles = async (dirPath: string): Promise<void> => {
  try {
    const entries = await fs.readdir(dirPath, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dirPath, entry.name);

      // Skip ignored directories
      const ignored = [
        "node_modules",
        ".git",
        ".DS_Store",
        ".webpack",
        ".cache",
        "dist",
        "out",
        "build",
        "coverage",
      ];

      if (ignored.some((ignore) => entry.name.includes(ignore))) {
        continue;
      }

      if (entry.isDirectory()) {
        await scanAndTrackFiles(fullPath);
      } else if (entry.isFile()) {
        try {
          const content = await fs.readFile(fullPath, "utf-8");
          const stats = await fs.stat(fullPath);
          fileSnapshots.set(fullPath, {
            content,
            mtime: stats.mtimeMs,
            hash: hashContent(content),
          });
        } catch (error) {
          // Skip files that can't be read (binary, etc.)
        }
      }
    }
  } catch (error) {
    console.error("Error scanning directory:", error);
  }
};

// Check if a file change was external and revert if needed
const handleFileChange = async (
  fullPath: string,
  eventType: string,
): Promise<void> => {
  // Ignore if this path is being written internally
  if (internalWritePaths.has(fullPath)) {
    return;
  }

  try {
    // Check if file exists
    const exists = fsSync.existsSync(fullPath);

    if (!exists) {
      // File was deleted externally
      const snapshot = fileSnapshots.get(fullPath);
      if (snapshot) {
        console.warn(
          `\n⚠️  [FileTracker] EXTERNAL DELETION DETECTED AND BLOCKED\n` +
            `File: ${fullPath}\n` +
            `This file was deleted by an external program or command.\n` +
            `The file has been automatically restored to protect the workspace.\n` +
            `Files in this workspace can ONLY be deleted within ScholarIDE.\n`,
        );

        // Restore the file
        internalWritePaths.add(fullPath);
        await fs.writeFile(fullPath, snapshot.content, "utf-8");
        setTimeout(() => internalWritePaths.delete(fullPath), 100);

        // Notify user
        if (
          mainWindow &&
          !mainWindow.isDestroyed() &&
          mainWindow.webContents &&
          !mainWindow.webContents.isDestroyed()
        ) {
          try {
            mainWindow.webContents.send("file-externally-modified", {
              filePath: fullPath,
              action: "restored-deleted",
            });
          } catch (e) {}
        }
      }
      return;
    }

    // File was modified or created
    const stats = await fs.stat(fullPath);
    const snapshot = fileSnapshots.get(fullPath);

    if (snapshot) {
      // File exists in our tracking - check if it was modified externally
      if (stats.mtimeMs > snapshot.mtime + 100) {
        // 100ms tolerance
        const currentContent = await fs.readFile(fullPath, "utf-8");
        const currentHash = hashContent(currentContent);

        if (currentHash !== snapshot.hash) {
          console.warn(
            `\n⚠️  [FileTracker] EXTERNAL EDIT DETECTED AND BLOCKED\n` +
              `File: ${fullPath}\n` +
              `This file was modified by an external program (VS Code, nano, vim, etc.)\n` +
              `The change has been automatically reverted to protect the workspace.\n` +
              `Files in this workspace can ONLY be edited within ScholarIDE.\n`,
          );

          // Revert to our snapshot
          internalWritePaths.add(fullPath);
          await fs.writeFile(fullPath, snapshot.content, "utf-8");
          setTimeout(() => internalWritePaths.delete(fullPath), 100);

          // Notify user
          if (
            mainWindow &&
            !mainWindow.isDestroyed() &&
            mainWindow.webContents &&
            !mainWindow.webContents.isDestroyed()
          ) {
            try {
              mainWindow.webContents.send("file-externally-modified", {
                filePath: fullPath,
                action: "reverted-modification",
              });
            } catch (e) {}
          }
        }
      }
    } else {
      // New file created externally - track it but allow it
      const content = await fs.readFile(fullPath, "utf-8");
      fileSnapshots.set(fullPath, {
        content,
        mtime: stats.mtimeMs,
        hash: hashContent(content),
      });
      console.log(`[FileTracker] New file tracked: ${fullPath}`);
    }
  } catch (error) {
    console.error(`[FileTracker] Error handling file change:`, error);
  }
};

const startWatching = (dirPath: string) => {
  if (currentWatcher) {
    currentWatcher.close();
    currentWatcher = null;
  }

  // Initial scan to track all files
  scanAndTrackFiles(dirPath).then(() => {
    console.log(
      `[FileTracker] Tracking ${fileSnapshots.size} files in workspace`,
    );
  });

  try {
    // Recursive watching is supported on macOS and Windows (mostly)
    currentWatcher = fsSync.watch(
      dirPath,
      { recursive: true },
      async (eventType, filename) => {
        const ignored = [
          "node_modules",
          ".git",
          ".DS_Store",
          ".webpack",
          ".cache",
          "dist",
          "out",
          "build",
          "coverage",
          "Thumbs.db", // Windows
        ];

        if (filename && ignored.some((ignore) => filename.includes(ignore))) {
          return;
        }

        // Build full path
        const fullPath = path.join(dirPath, filename);

        // Handle the file change (check for external edits)
        await handleFileChange(fullPath, eventType);

        // Still send the event to renderer for UI updates
        if (
          mainWindow &&
          !mainWindow.isDestroyed() &&
          mainWindow.webContents &&
          !mainWindow.webContents.isDestroyed()
        ) {
          try {
            mainWindow.webContents.send("file-system-changed", {
              eventType,
              filename,
            });
          } catch (e) {}
        }
      },
    );
  } catch (error) {
    console.error("Failed to start watcher:", error);
  }
};

// Return the workspace path (no dialog - always use workspace)
ipcMain.handle("open-directory", async () => {
  const workspacePath = getWorkspacePath();
  startWatching(workspacePath);
  return workspacePath;
});

// Called by the renderer when the user logs in or out.
// Sets the active user ID so workspace paths become user-scoped.
ipcMain.handle("set-user-id", async (_event, userId: string | null) => {
  currentUserId = userId;
  const workspacePath = getWorkspacePath();

  if (userId) {
    // Ensure the user's workspace directory exists
    await fs.mkdir(workspacePath, { recursive: true });
    // Seed a welcome file if the workspace is brand new
    const welcomeFile = path.join(workspacePath, "welcome.md");
    try {
      await fs.access(welcomeFile);
    } catch {
      await fs.writeFile(
        welcomeFile,
        `# Welcome to ScholarIDE!\n\nThis is your personal workspace. Happy coding!\n`,
        "utf-8",
      );
    }
  }

  currentTerminalCwd = workspacePath;
  return workspacePath;
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", async () => {
  // Register deep link protocol for OAuth callbacks (e.g. scholaride://auth/callback)
  if (process.defaultApp) {
    // Development: pass the app path as an argument
    app.setAsDefaultProtocolClient('scholaride', process.execPath, [app.getAppPath()]);
  } else {
    app.setAsDefaultProtocolClient('scholaride');
  }

  // Override the CSP header injected by the webpack dev server so that
  // the renderer is allowed to connect to Supabase.
  const { session } = require("electron");
  session.defaultSession.webRequest.onHeadersReceived(
    (details: Electron.OnHeadersReceivedListenerDetails, callback: (response: Electron.HeadersReceivedResponse) => void) => {
    const supabaseUrl = process.env.SUPABASE_URL || "https://edepqvyytyygdztctzeq.supabase.co";
    const supabaseWss = supabaseUrl.replace(/^http/, "ws");
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        "Content-Security-Policy": [
          `default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' ${supabaseUrl} ${supabaseWss}; worker-src 'self' blob:; font-src 'self' data:;`,
        ],
      },
    });
  });

  await initializeWorkspace();
  createWindow();
  createPty(getWorkspacePath());
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

// Handle macOS deep links (app already running)
app.on('open-url', (event, url) => {
  event.preventDefault();
  if (mainWindow && !mainWindow.isDestroyed() && mainWindow.webContents && !mainWindow.webContents.isDestroyed()) {
    try {
      mainWindow.webContents.send('oauth-callback', url);
    } catch (e) {}
  }
});

// Handle Windows/Linux deep links (second instance triggered)
app.on('second-instance', (_event, commandLine) => {
  const url = commandLine.find(arg => arg.startsWith('scholaride://'));
  if (url && mainWindow && !mainWindow.isDestroyed()) {
    try {
      mainWindow.webContents.send('oauth-callback', url);
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    } catch (e) {}
  }
});

