import { app, BrowserWindow, ipcMain } from "electron";
import * as fs from "fs/promises";
import * as path from "path";
import * as pty from "node-pty";
import * as os from "os";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let ptyProcess: any = null;
let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    titleBarStyle: process.platform === "darwin" ? "hiddenInset" : "default",
    titleBarOverlay:
      process.platform !== "darwin"
        ? {
            color: "#252526",
            symbolColor: "#cccccc",
          }
        : false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  // Setup terminal
  const createPty = (cwd: string) => {
    if (ptyProcess) {
      ptyProcess.kill();
    }

    const shell = process.platform === "win32" ? "powershell.exe" : "zsh";
    const args = process.platform === "win32" ? [] : ["-l"];

    const env = { ...process.env, TERM: "xterm-256color" };
    // Remove npm_config_prefix which can mess up nvm in the integrated terminal
    delete (env as any).npm_config_prefix;

    ptyProcess = pty.spawn(shell, args, {
      name: "xterm-color",
      cols: 80,
      rows: 24,
      cwd: cwd,
      env: env as any,
    });

    ptyProcess.onData((data: string) => {
      mainWindow?.webContents.send("terminal-data", data);
    });
  };

  createPty(process.env.HOME);

  ipcMain.on("terminal-input", (event, data) => {
    if (ptyProcess) ptyProcess.write(data);
  });

  ipcMain.on("terminal-resize", (event, { cols, rows }) => {
    if (ptyProcess) ptyProcess.resize(cols, rows);
  });

  ipcMain.on("terminal-set-cwd", (event, cwd) => {
    createPty(cwd);
  });

  // Native Menu Setup for Mac
  const { Menu } = require("electron");
  const template: any[] = [
    ...(process.platform === "darwin"
      ? [
          {
            label: app.name,
            submenu: [
              { role: "about" },
              { type: "separator" },
              { role: "services" },
              { type: "separator" },
              { role: "hide" },
              { role: "hideOthers" },
              { role: "unhide" },
              { type: "separator" },
              { role: "quit" },
            ],
          },
        ]
      : []),
    {
      label: "File",
      submenu: [
        {
          label: "Open Folder...",
          accelerator: "CmdOrCtrl+O",
          click: () => mainWindow?.webContents.send("menu-open-folder"),
        },
        { type: "separator" },
        { role: "quit" },
      ],
    },
    {
      label: "Edit",
      submenu: [
        { role: "undo" },
        { role: "redo" },
        { type: "separator" },
        { role: "cut" },
        { role: "copy" },
        { role: "paste" },
      ],
    },
    {
      label: "View",
      submenu: [
        { role: "reload" },
        { role: "forceReload" },
        { role: "toggleDevTools" },
        { type: "separator" },
        { role: "resetZoom" },
        { role: "zoomIn" },
        { role: "zoomOut" },
        { type: "separator" },
        { role: "togglefullscreen" },
      ],
    },
  ];

  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);
};

// IPC Handlers
ipcMain.handle("list-directory", async (event, dirPath) => {
  const absolutePath = path.isAbsolute(dirPath)
    ? dirPath
    : path.join(app.getAppPath(), dirPath);
  try {
    const entries = await fs.readdir(absolutePath, { withFileTypes: true });
    return entries
      .filter((entry) => !entry.name.startsWith("."))
      .map((entry) => ({
        name: entry.name,
        isDirectory: entry.isDirectory(),
        path: path.resolve(absolutePath, entry.name),
      }));
  } catch (error) {
    console.error("Error listing directory:", error);
    return [];
  }
});

ipcMain.handle("read-file", async (event, filePath) => {
  const absolutePath = path.isAbsolute(filePath)
    ? filePath
    : path.join(app.getAppPath(), filePath);
  try {
    return await fs.readFile(absolutePath, "utf-8");
  } catch (error) {
    console.error("Error reading file:", error);
    throw error;
  }
});

ipcMain.handle("write-file", async (event, filePath, content) => {
  const absolutePath = path.isAbsolute(filePath)
    ? filePath
    : path.join(app.getAppPath(), filePath);
  try {
    await fs.writeFile(absolutePath, content, "utf-8");
    return true;
  } catch (error) {
    console.error("Error writing file:", error);
    throw error;
  }
});

ipcMain.handle("create-file", async (event, filePath) => {
  const absolutePath = path.isAbsolute(filePath)
    ? filePath
    : path.join(app.getAppPath(), filePath);
  try {
    await fs.writeFile(absolutePath, "", "utf-8");
    return true;
  } catch (error) {
    console.error("Error creating file:", error);
    throw error;
  }
});

ipcMain.handle("get-app-path", () => {
  return app.getAppPath();
});

ipcMain.handle("open-directory", async () => {
  const { dialog } = require("electron");
  const result = await dialog.showOpenDialog({
    properties: ["openDirectory"],
  });
  if (result.canceled) return null;
  return result.filePaths[0];
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
